"use client";
import Image from "next/image";
import type { CSSProperties, PointerEvent } from "react";
import { useEffect, useRef, useState } from "react";
const STIFFNESS=210,DAMPING=11;
const resist=(v:number)=>v<0?-Math.min(.1,Math.abs(v)/(1+Math.abs(v)*8)):v>1?1+Math.min(.1,(v-1)/(1+(v-1)*8)):v;
export default function PostTemperature({likes,dislikes,interactive=true}:{likes:number;dislikes:number;interactive?:boolean}){
 const total=likes+dislikes,baseHome=total?dislikes/total:.5; const [aggregateHome,setAggregateHome]=useState<number|null>(null),home=aggregateHome??baseHome; const [position,setPosition]=useState(home); const trackRef=useRef<HTMLDivElement>(null),frameRef=useRef<number|null>(null),positionRef=useRef(home),velocityRef=useRef(0),postIdRef=useRef<string|null>(null),dragRef=useRef({active:false,lastX:home,lastTime:0,startX:home});
 const style={"--temperature-position":`${Math.max(-.1,Math.min(1.1,position))*100}%`,"--temperature-home":`${home*100}%`} as CSSProperties;
 useEffect(()=>()=>{if(frameRef.current)cancelAnimationFrame(frameRef.current)},[]);
 useEffect(()=>{if(!dragRef.current.active){velocityRef.current=0;positionRef.current=home;setPosition(home)}},[home]);
 useEffect(()=>{if(!interactive)return;const match=window.location.pathname.match(/^\/post\/([^/]+)\/?$/);if(!match)return;const postId=decodeURIComponent(match[1]);postIdRef.current=postId;let active=true;void fetch(`/api/posts/${encodeURIComponent(postId)}/temperature`,{cache:"no-store"}).then(async response=>response.ok?response.json():null).then((data:{count?:number;average?:number}|null)=>{if(!active||!data||!Number.isFinite(data.average)||!data.count)return;setAggregateHome(Math.max(0,Math.min(1,Number(data.average)/100)))}).catch(()=>undefined);return()=>{active=false;postIdRef.current=null}},[interactive]);
 function update(e:PointerEvent<HTMLDivElement>){const r=trackRef.current?.getBoundingClientRect();if(!r?.width)return;const now=performance.now(),next=resist((e.clientX-r.left)/r.width),dt=Math.max(16,now-dragRef.current.lastTime)/1000;velocityRef.current=(next-dragRef.current.lastX)/dt;dragRef.current={...dragRef.current,active:true,lastX:next,lastTime:now};positionRef.current=next;setPosition(next)}
 function settle(){let last=performance.now();const tick=(now:number)=>{const dt=Math.min(.032,(now-last)/1000);last=now;velocityRef.current+=(-STIFFNESS*(positionRef.current-home)-DAMPING*velocityRef.current)*dt;const next=positionRef.current+velocityRef.current*dt;positionRef.current=next;setPosition(next);if(Math.abs(velocityRef.current)<.003&&Math.abs(next-home)<.0015){velocityRef.current=0;positionRef.current=home;setPosition(home);frameRef.current=null}else frameRef.current=requestAnimationFrame(tick)};frameRef.current=requestAnimationFrame(tick)}
 async function record(value:number){const postId=postIdRef.current;if(!postId)return;try{const response=await fetch(`/api/posts/${encodeURIComponent(postId)}/temperature`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({value:Math.round(Math.max(0,Math.min(1,value))*100)})});if(!response.ok)return;const data=await response.json() as {count?:number;average?:number};if(data.count&&Number.isFinite(data.average))setAggregateHome(Math.max(0,Math.min(1,Number(data.average)/100)))}catch{/* 반응 저장 실패가 슬라이더 조작을 막지 않습니다. */}}
 function start(e:PointerEvent<HTMLDivElement>){if(!interactive)return;e.preventDefault();if(frameRef.current)cancelAnimationFrame(frameRef.current);dragRef.current={active:true,lastX:positionRef.current,lastTime:performance.now(),startX:positionRef.current};e.currentTarget.setPointerCapture(e.pointerId);update(e)}
 function end(e:PointerEvent<HTMLDivElement>){if(!interactive||!dragRef.current.active)return;const value=Math.max(0,Math.min(1,positionRef.current)),moved=Math.abs(value-dragRef.current.startX)>=.015;dragRef.current.active=false;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(moved)void record(value);settle()}
 return <div className={`post-temperature${interactive?" interactive":""}`} style={style} aria-label="게시글 반응 온도"><div className="temperature-copy"><span>OK</span><span>Not OK</span></div><div ref={trackRef} className="temperature-track" role="img" aria-label={`Not OK 방향 ${Math.round(home*100)}%`} onPointerDown={start} onPointerMove={e=>interactive&&dragRef.current.active&&update(e)} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={end}><span className="temperature-fill"/><span className="temperature-home"/><span className="temperature-marker"><Image src="/jinju-pearl-cutout.png" alt="" width={28} height={28} draggable={false}/></span></div></div>
}
